export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'an astronaut scuba diving in a coral reef on a distant exoplanet, photorealistic',
  'a marble sculpture of a hummingbird mid-flight, classical style',
  'a neon sign shaped like a melting ice cream cone in a cyberpunk city alley',
  'a watercolor painting of a vineyard at sunrise with mist rolling through, impressionist',
  'a retro 1950s diner scene with robots serving milkshakes, cinematic lighting',
  'an abstract digital artwork of human emotions represented as swirling color fields',
  'a steampunk mechanical octopus exploring a sunken pirate ship, digital painting',
  'a fashion illustration of a futuristic gown made of holographic fabric',
  'a chalk pastel drawing of children chasing butterflies in a flower meadow',
  'a high-speed macro shot of a drop of red wine hitting a crystal glass',
  'a photo-realistic CGI of a floating castle made of clouds at sunset',
  'a silhouette of a dancer against a backdrop of fireworks, vector art',
  'a pencil sketch of an ancient tree with faces carved into its bark',
  'a 3D isometric illustration of a miniature city inside a teacup',
  'a hyper-detailed concept art of a dragon curled around a futuristic spaceship',
  'a vintage propaganda poster for a Mars colonization mission',
  'a surreal collage of melting clocks and blooming flowers in pastel tones',
  'a cinematic shot of a neon-lit street market in Tokyo during rain',
  'a polaroid-style photo of a group of flamingos wearing sunglasses',
  'a fantasy landscape of floating islands connected by waterfalls, digital art',
  'a vector infographic of the solar system with playful cartoon planets',
  'an infrared photograph of a desert with ghostly vegetation',
  'a gothic stained glass window depicting a phoenix rising from ashes',
  'a woodcut illustration of Vikings sailing under a blood-red moon',
  'a close-up portrait of an android with translucent skin showing circuitry',
  'a cel-shaded anime scene of a samurai facing off against a giant robot',
  'a time-lapse style render of a rose blooming in the desert',
  'a macro photo of frost patterns on a car window at dawn',
  'an oil painting of a jazz band performing in a smoky 1920s speakeasy',
  'a minimalist poster for a fictional space opera movie',
];